-- 006_hipaa_gdpr_hardening.sql
-- Fixes found during HIPAA/GDPR review (see README "Compliance hardening — this pass").

-- FIX 1 (audit_log.actor_user_id's missing ON DELETE SET NULL, which made
-- subscriber.controller.js's deleteMyAccount() -- the GDPR/CCPA
-- right-to-erasure endpoint -- fail for every account, since
-- auth.controller.js's register() always writes an audit_log row
-- referencing the new user) is fixed directly in migration 004, not
-- here. Nothing has been deployed against a real database yet (see
-- README roadmap), so there's no already-applied migration to patch
-- around -- editing 004 in place is cleaner than an ALTER ... DROP
-- CONSTRAINT here guessing at Postgres's autogenerated constraint name.
-- Reproduced against the real migration SQL via pg-mem before the fix
-- (see verify/deletion_fk_repro.js): DELETE FROM users raised
-- "violates foreign key constraint ... on table audit_log". Confirmed
-- fixed after, using the same repro.

-- ---------------------------------------------------------------------
-- FIX 2: encryption-at-rest, defense-in-depth for the two columns most
-- likely to carry identifiable health narrative or lab values.
-- Provider-level storage encryption (e.g. RDS/Cloud SQL encrypted
-- volumes) is still the primary control and is a deployment setting,
-- not something this migration can enforce -- see README. This adds
-- application-layer AES-256-GCM encryption (src/lib/fieldEncryption.js)
-- as a second layer for the fields most likely to contain PHI text,
-- so a raw disk or backup snapshot leak alone isn't sufficient to
-- expose them.
--
-- lab_results.value was DECIMAL; it now holds ciphertext, so it becomes
-- TEXT. Dropped and re-added rather than ALTER COLUMN ... TYPE ... USING:
-- this table has no production rows yet (self-reported lab
-- reconciliation was never wired to the frontend -- see migration 002),
-- so there's nothing to cast, and drop+add keeps this migration
-- runnable against both real Postgres and the pg-mem harness the test
-- suite uses (tests/setup.js runs these files verbatim), which does not
-- implement the USING clause. unit was already TEXT -- no change needed.
ALTER TABLE lab_results DROP COLUMN value;
ALTER TABLE lab_results ADD COLUMN value TEXT NOT NULL;

COMMENT ON COLUMN lab_results.value IS
  'AES-256-GCM ciphertext (base64), not plaintext. Encrypt/decrypt only via src/lib/fieldEncryption.js. Still governed by the hard rule in migration 002: no scoring function may ever read this table.';
COMMENT ON COLUMN lab_results.unit IS
  'Plaintext (e.g. "mg/L") -- a unit label alone does not identify anyone. Only value is encrypted.';

-- case_entries.change_summary is already TEXT -- no type change needed,
-- application layer now writes ciphertext into it instead of plaintext.
COMMENT ON COLUMN case_entries.change_summary IS
  'AES-256-GCM ciphertext (base64), not plaintext. Encrypt/decrypt only via src/lib/fieldEncryption.js. subscriber_case_code is NOT encrypted -- it is already an anonymised display code (e.g. CASE-000123), not identifying on its own.';

-- ---------------------------------------------------------------------
-- FIX 3: sessions have no bound on how long stale rows accumulate.
-- expires_at already stops an expired session from authenticating, but
-- rows past expiry are never removed, so the table -- which includes
-- ip_address and user_agent, both personal data under GDPR -- grows
-- forever. Purging is handled by src/lib/retention.js, run as a
-- scheduled job in production (NOT wired to auto-run here -- see
-- README). audit_log is deliberately EXCLUDED from any purge job: HIPAA
-- generally requires audit trail retention (commonly 6 years), so
-- retention there is a MINIMUM-keep requirement, not a purge target.
